name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: "macos-latest"
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build and publish
        run: uv publish
        working-directory: israwave
        env:
          # Get token from https://pypi.org/manage/account/token/
          # Set token in https://github.com/thewh1teagle/nakdimon-ort/settings/secrets/actions/new
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}